### ISSUE TITLE
set.scan ... self.live.query("/live/tracks")[0]  IndexError: list index out of range

### ISSUE THREAD

**Issue by transfluxus** [ideoforms/pylive#4]
Hi using python 2.7 and ableton live with LiveOSC2
I'm getting this
  ```File "/Users/someuser/live/venv/lib/python2.7/site-packages/live/set.py", line 319, in num_tracks
    return self.live.query("/live/tracks")[0]
IndexError: list index out of range```

**Comment by bafonso** [comment]
I'm getting the same :)

**Comment by ideoforms** [comment]
Hi there,

This is typically because pylive can't reach the LiveOSC server. This can be because:
 - the version of LiveOSC you are using does not support your version of Live (which was the case with most forks of LiveOSC); or
 - you are running LiveOSC2, which pylive is not compatible with.

I recommend using my fork of LiveOSC here:
https://github.com/ideoforms/LiveOSC
